package com.ordernest.order.entity;

public enum OrderEventType {
    ORDER_CREATED,
    ORDER_STATUS_CHANGED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    SHIPMENT_CREATED,
    SHIPMENT_SHIPPED,
    SHIPMENT_DELIVERED,
    SHIPMENT_RETURNED,
    ORDER_CANCELLED,
    EMAIL_NOTIFICATION_QUEUED
}
